name: example
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  polar:
    git:
      prs:
        - https://github.com/Rexios80/polar/pulls/14
      url: https://github.com/Rexios80/polar
