name: git_dependency_prs
description: Link PRs to git dependencies. Generate update timelines and enforce compliance.
version: 0.3.0
homepage: https://github.com/IO-Design-Team/git_dependency_prs

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  ansicolor: ^2.0.1
  github: ^9.7.0
  pub_api_client: ^2.3.0
  yaml: ^3.1.1
  timeago: ^3.3.0
  intl: ^0.19.0
  args: ^2.3.2
  pub_update_checker: ^1.2.0

dev_dependencies:
  rexios_lints: ^6.0.1
  test: ^1.25.7

executables:
  git_dependency_prs: git_dependency_prs
